services:
  vs:
    image: ghcr.io/tmforum-rand/vs_docker_images/tmf785-vs-v1:latest
    ports:
      - "9000:9000"
    networks:
      - tmf

  api-gateway:
    image: nginx:alpine
    ports:
      - "8785:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - vs
    networks:
      - tmf

networks:
  tmf:
    external: true